language: node_js

node_js:
- 6

addons:
  ssh_known_hosts: 138.197.10.138

branches:
  only:
  - master

before_deploy:
- openssl aes-256-cbc -K $encrypted_d7efcf8543e5_key -iv $encrypted_d7efcf8543e5_iv
  -in ofjamescole_deploy_rsa.enc -out /tmp/ofjamescole_deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/ofjamescole_deploy_rsa
- ssh-add /tmp/ofjamescole_deploy_rsa

deploy:
- hexo deploy

before_install:
- npm install -g hexo

install:
- npm install

script:
- hexo generate
