# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
bio:
  - I began web developing in 2006 while completing my Bachelor's degree. It was just a hobby at the time, for extra cash. Yet after graduation, it soon became a full-time career. Since 2008, I've been a professional web developer working on a variety of technologies and languages, from .NET to Drupal, and JavaScript to Ruby.
  - In practice, I'm a full stack developer, and I like getting my hands dirty wherever possible. My favorite technologies are those for the front-end, like D3, Angular, React, and Polymer. When not programming, I like making cheese, biking, and walking my dog.
  - Look over my projects, or read some of my writings.

per_page: 9

# Sidebar
sidebar: true
widgets:
- recent_posts
- archive
- tag
- category
- tagcloud

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter: jemilco
google_plus:
fb_admins:
fb_app_id:
