# Header
menu:
  About: about
  Portfolio: portfolio
  Writings: writings
rss: /atom.xml

# Content
excerpt_link: Read More

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
